### ISSUE TITLE
如何打包linux下的QT包

### ISSUE THREAD

**Issue by chenguang3312** [chengyangkj/Ros_Qt5_Gui_App#11]
你好，古月居4期课程全部买了，第四期说到windows打包问题，linux 下qtcreate 怎么进行打包，release时候一直报错，请问linux下的打包如何做，专题论坛上也没人问，有QQ群或者微信群吗。方便的话留个QQ出个博客也可以。

**Comment by chengyangkj** [comment]
QQ群&nbsp;797497206
linux打包ROS没有尝试过，按照网上的linux打包qt项目教程走即可，当然也需要打包ros相关动态库，图像卡顿问题可订阅压缩后的图像，我github上 readme有写





------------------ 原始邮件 ------------------
发件人: Mr.chen <notifications@github.com&gt;
发送时间: 2021年1月6日 16:34
收件人: chengyangkj/Ros_Qt5_Gui_App <Ros_Qt5_Gui_App@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[chengyangkj/Ros_Qt5_Gui_App] 如何打包linux下的QT包 (#11)





 
你好，古月居4期课程全部买了，第四期说到windows打包问题，linux 下qtcreate 怎么进行打包，release时候一直报错，请问linux下的打包如何做，专题论坛上也没人问，有QQ群或者微信群吗。方便的话留个QQ出个博客也可以。
