### ISSUE TITLE
显示的坐标和原始rviz的坐标不匹配

### ISSUE THREAD

**Issue by leigetiwen** [chengyangkj/Ros_Qt5_Gui_App#12]
我监听鼠标的坐标信息，转换为全局坐标后发现，显示地图的原点在左下角，而原始的rviz的(map)地图左下角是yaml中x,y的值。是什么原因导致这个差别的呢

**Comment by chengyangkj** [comment]
> 我监听鼠标的坐标信息，转换为全局坐标后发现，显示地图的原点在左下角，而原始的rviz的(map)地图左下角是yaml中x,y的值。是什么原因导致这个差别的呢

哪个分支

**Comment by leigetiwen** [comment]
master分支

**Comment by chengyangkj** [comment]
> master分支

涉及到图元坐标系与map坐标系的转换，可以参考echart分支代码，里面进行了转换，不过是自绘制的地图，没用到librviz

**Comment by leigetiwen** [comment]
好的，谢谢
