### ISSUE TITLE
关于使用QGraphicsView绘制雷达地图显示的具体过程是如何实现的，我没怎么看懂，想问问有没有其他demo

### ISSUE THREAD

**Issue by lingxd** [chengyangkj/Ros_Qt5_Gui_App#15]

**Comment by chengyangkj** [comment]
雷达主要就是:
订阅话题->解析数据->坐标变换(变换到地图坐标系)->图层坐标转换（地图坐标系转换到界面显示的图元坐标系）
地图就比较简单了:
订阅话题->解析数据->存储成图片（图元坐标系）->显示图片

主要需要注意的是坐标变换

简单点的demo的话可以看这个分支：https://github.com/chengyangkj/Ros_Qt5_Gui_App/tree/qml_hmi
但是是使用qml作为显示，原理相同，其中雷达话题的坐标变换没处理好，还没来得及维护

**Comment by lingxd** [comment]
谢谢
