### ISSUE TITLE
关于在远程端进行连接不上机器人的问题

### ISSUE THREAD

**Issue by ju-mingyue** [chengyangkj/Ros_Qt5_Gui_App#19]
我现在对于软件的使用存在以下几个疑问：
1、本软件是否只能安装在机器人自身的工控机内？

2、我使用ubuntu18的上位机远程连接机器人的工控机（jetsonnano），我需要把这个软件安装在哪一端呢？如果安装在笔记本上位机端，我需要怎样配置才能连接到机器人上。目前我安装在笔记本端，但是无法连接到机器人。

**Comment by chengyangkj** [comment]
使用ros多机通信原理，安装在任意一台配置好ros分布式通信的电脑上即可
安装在笔记本或工控机均可，关于配置github readme写的很清楚
建议先去看看ros多机通信原理




------------------ 原始邮件 ------------------
发件人: mingyue ***@***.***&gt;
发送时间: 2021年7月28日 11:41
收件人: chengyangkj/Ros_Qt5_Gui_App ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[chengyangkj/Ros_Qt5_Gui_App] 关于在远程端进行连接不上机器人的问题 (#19)





 
我现在对于软件的使用存在以下几个疑问：
 1、本软件是否只能安装在机器人自身的工控机内？
 
2、我使用ubuntu18的上位机远程连接机器人的工控机（jetsonnano），我需要把这个软件安装在哪一端呢？如果安装在笔记本上位机端，我需要怎样配置才能连接到机器人上。目前我安装在笔记本端，但是无法连接到机器人。

**Comment by ju-mingyue** [comment]
当我按照运行方法配置时：
![深度截图_cyrobot_monitor_20210728120412](https://user-images.githubusercontent.com/81499872/127261953-7eca05e3-f622-4218-ac7f-d054048c3762.png)

出现的问题如下：
![深度截图_gnome-terminal-server_20210728120516](https://user-images.githubusercontent.com/81499872/127261969-0a149fcd-e802-47c6-a0fb-4036641e2342.png)
