### ISSUE TITLE
undefined reference to `cv::Mat::Mat(int, int, int)

### ISSUE THREAD

**Issue by jianbuzhang** [chengyangkj/Ros_Qt5_Gui_App#22]
**bug描述**
when I run "catkin_make",it reported:undefined reference to `cv::Mat::Mat(int, int, int);
**操作步骤**

**分支名及平台:**
 - 平台: [ubuntu ]
 - 分支名 [e.g. chrome, safari]

**Comment by jianbuzhang** [comment]
CMakeFiles/cyrobot_monitor.dir/src/qnode.cpp.o: In function `cyrobot_monitor::QNode::mapCallback(boost::shared_ptr<nav_msgs::OccupancyGrid_<std::allocator<void> > const>)':
qnode.cpp:(.text+0x46e4): undefined reference to `cv::Mat::Mat(int, int, int)'
CMakeFiles/cyrobot_monitor.dir/src/qnode.cpp.o: In function `cyrobot_monitor::QNode::RotaMap(cv::Mat const&)':
qnode.cpp:(.text+0x75cc): undefined reference to `cv::Mat::Mat()'
qnode.cpp:(.text+0x7606): undefined reference to `cv::Mat::create(cv::Size_<int>, int)'
CMakeFiles/cyrobot_monitor.dir/src/qnode.cpp.o: In function `cyrobot_monitor::QNode::QImage2Mat(QImage&)':
qnode.cpp:(.text+0x7ac7): undefined reference to `cv::Mat::Mat()'
CMakeFiles/cyrobot_monitor.dir/src/qnode.cpp.o: In function `cv::Mat::operator=(cv::Mat&&)':
qnode.cpp:(.text._ZN2cv3MataSEOS0_[_ZN2cv3MataSEOS0_]+0x2c): undefined reference to `cv::Mat::release()'
collect2: error: ld returned 1 exit status

**Comment by zhongguanLiu** [comment]
请问你解决这个问题了吗？能否给出以下解决思路和步骤？

**Comment by IricEmage** [comment]
I have the same problem when I build with catkin_make. Have you already solved this?

**_CMakeFiles/ros_qt5_gui_app.dir/src/qnode.cpp.o: In function `ros_qt5_gui_app::QNode::QImage2Mat(QImage&)':
qnode.cpp:(.text+0x777f): undefined reference to `cv::Mat::Mat()'
collect2: error: ld returned 1 exit status_**

**Comment by jianlaili** [comment]
> 

请问大佬有解决这个问题吗，我也遇到了
