### ISSUE TITLE
点击连接按钮后界面闪退

### ISSUE THREAD

**Issue by willzoe** [chengyangkj/Ros_Qt5_Gui_App#3]
当我运行程序，如下图所示填写好`主节点地址`和`本机IP`之后，点击`连接`按钮，程序界面会发生闪退。
![Screenshot from 2020-05-09 04-20-41](https://user-images.githubusercontent.com/14708901/81446572-c3e29e80-91ad-11ea-8c77-8f073000590a.png)

**Comment by chengyangkj** [comment]
由于我开发的版本是melodic版本，并未在kinetic版本测试,librviz库bug比较多，会无缘无故发生闪退，这两天正在修复中------------------ 原始邮件 ------------------
发件人: "willzoe"<notifications@github.com>
发送时间: 2020年5月9日(星期六) 凌晨4:30
收件人: "chengyangkj/Ros_Qt5_Gui_App"<Ros_Qt5_Gui_App@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [chengyangkj/Ros_Qt5_Gui_App] 点击连接按钮后界面闪退 (#3)




 
当我运行程序，如下图所示填写好主节点地址和本机IP之后，点击连接按钮，程序界面会发生闪退。
 
 
&mdash;

**Comment by chengyangkj** [comment]
> 当我运行程序，如下图所示填写好`主节点地址`和`本机IP`之后，点击`连接`按钮，程序界面会发生闪退。
> ![Screenshot from 2020-05-09 04-20-41](https://user-images.githubusercontent.com/14708901/81446572-c3e29e80-91ad-11ea-8c77-8f073000590a.png)

已更新kinetic版本分支，具体功能暂未测试，欢迎测试并提交bug
https://github.com/chengyangkj/Ros_Qt5_Gui_App/tree/kinetic-devel

**Comment by liliangbin** [comment]
emmm，大佬我有fork你的这个项目，然后觉得有可能可以做个docker的形式，避免了那些奇奇怪怪的问题。

**Comment by willzoe** [comment]
不好意思，之前比较忙，没有来得及做测试。

今天测试的时候发现，当我把工程克隆到工作空间并且切换到kinetic分支后，工作空间的路径在`$ROS_PACKAGE_PATH`中消失了，并且找不到命令`catkin_make`和`catkin_create_qt_pkg`。

之前我也遇到过类似的问题，是因为创建的功能包依赖了一些其他的不恰当的功能包。

**Comment by willzoe** [comment]
问题好像是因为qrcreator。

当我在新创建的工作空间中使用命令`catkin_make`编译功能包后，一切正常。

当我使用指令`qtcreator`启动Qtcreator，对功能包再次编译并退出Qtcreator之后，在启动Qtcreator的终端中仍然可以看到工作空间的路径在`$ROS_PACKAGE_PATH`中，并且可以对功能包正确编译。

但是当我再开启一个终端后，工作空间的路径在`$ROS_PACKAGE_PATH`就看不到了，并且`catkin_make`也无法执行。
