### ISSUE TITLE
上位机如何控制工控机？

### ISSUE THREAD

**Issue by ergo-zyh** [chengyangkj/Ros_Qt5_Gui_App#4]
我借助您的代码想学习如何利用上位机通过WIFI远程控制工控机，进而控制四轮小车，想问问这一部分是不是就是您代码里到connection部分？

**Comment by chengyangkj** [comment]
> 我借助您的代码想学习如何利用上位机通过WIFI远程控制工控机，进而控制四轮小车，想问问这一部分是不是就是您代码里到connection部分？

使用这个软件需先配置好机器人，只是进行可视化了

**Comment by ergo-zyh** [comment]
我已经将控制规划的代码写好了，现在就是想再写一个上位机，方便改参和调试。想问问您给机器人WIFI通讯那部分的qt回调函数应该怎么实现

**Comment by chengyangkj** [comment]
> 我已经将控制规划的代码写好了，现在就是想再写一个上位机，方便改参和调试。想问问您给机器人WIFI通讯那部分的qt回调函数应该怎么实现

使用ROS创建的Qt功能包，本人在古月学院有相关专题课程，可以看下：https://class.guyuehome.com/detail/p_5eba414d58533_Uh4XTbPi/6

**Comment by ergo-zyh** [comment]
谢谢您的回答~
