### ISSUE TITLE
直接运行和编译后运行都报错“getTrasnsform error from:base_link to:map error:"map" passed to lookupTransform argument target_frame does not exist.”

### ISSUE THREAD

**Issue by fxt-7** [chengyangkj/Ros_Qt5_Gui_App#40]
getTrasnsform error from:base_link to:map error:"map" passed to lookupTransform argument target_frame does not exist.
地图界面无法显示

**Comment by chengyangkj** [comment]
你的机器人底盘没有启动，或者系统中tf坐标变换有问题，导致没有监听到map的坐标变换

**Comment by 7yzx** [comment]
非常抱歉，在close的分支下继续提问，但是我遇到了相同的问题，应该也是tf坐标变换的问题，但是我有`map`-->`odom`-->`base_link`，下面是我的监听结果，请问这里是什么问题呢

![image](https://github.com/user-attachments/assets/2a545047-76e7-4e0f-85f0-15ba7c8d1ea4)

**Comment by DopeRita** [comment]
> getTrasnsform error from:base_link to:map error:"map" passed to lookupTransform argument target_frame does not exist. 地图界面无法显示

你好，请问解决了吗？我也遇到了同样的问题。
