### ISSUE TITLE
请问如何将moveit的display加入到界面中？

### ISSUE THREAD

**Issue by shipengqq** [chengyangkj/Ros_Qt5_Gui_App#5]

**Comment by shipengqq** [comment]
no problem

**Comment by chengyangkj** [comment]
没有研究过机械臂，但是原理都是一样的，查看添加了哪些rviz的disply，然后在代码中添加即可------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;robot_qq&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月22日(星期一) 晚上8:50
收件人:&nbsp;&quot;chengyangkj/Ros_Qt5_Gui_App&quot;<Ros_Qt5_Gui_App@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [chengyangkj/Ros_Qt5_Gui_App] 请问如何将moveit的display加入到界面中？ (#5)
