### ISSUE TITLE
RVIZ problem

### ISSUE THREAD

**Issue by ANDUES** [chengyangkj/Ros_Qt5_Gui_App#8]
開發者您好

再使用您的GUI介面時發現RVIZ的選項都無法選取與檢視請問是甚麼原因呢(目前沒有連上車子是因為這樣嗎XD

**Comment by chengyangkj** [comment]
是的，因为没连接上master，rviz不能使用------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ANDUES&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月2日(星期三) 中午12:25
收件人:&nbsp;&quot;chengyangkj/Ros_Qt5_Gui_App&quot;<Ros_Qt5_Gui_App@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[chengyangkj/Ros_Qt5_Gui_App] RVIZ problem (#8)
