### ISSUE TITLE
rviz画bezier

### ISSUE THREAD

**Issue by sweetquiet** [chengyangkj/Ros_Qt5_Gui_App#9]
你好，请问如何在rviz里画曲线呢，就像CAD那样画线

**Comment by WelinLee** [comment]
可以的，比较复杂，要改costmap 2d，看放在哪一层。还要再写一个消息用于广播地图信息，地图里面包含贝塞尔曲线信息。或者你直接广播曲线信息也可以，一般也就包含四个点。
